2025-10-05 23:35:33,225 [ERROR] Traceback (most recent call last):
  File "C:\Users\abdoh\Downloads\testScript\python\extract_bubbles_by_images_ai.py", line 51, in <module>
    ocr = PaddleOCR(use_angle_cls=True, lang=lang, use_gpu=False)
  File "C:\Users\abdoh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\paddleocr\_pipelines\ocr.py", line 163, in __init__
    super().__init__(**base_params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\abdoh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\paddleocr\_pipelines\base.py", line 63, in __init__
    self._common_args = parse_common_args(
                        ~~~~~~~~~~~~~~~~~^
        common_args, default_enable_hpi=_DEFAULT_ENABLE_HPI
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\abdoh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\paddleocr\_common_args.py", line 43, in parse_common_args
    raise ValueError(f"Unknown argument: {name}")
ValueError: Unknown argument: use_gpu

2025-10-05 23:35:33,226 [INFO] === üèÅ Finished detector script ===
